triggers:
- envs: []
  last_enabled_at: 2024-02-08 21:38:45.155356
  name: daily morning run
  pipeline_uuid: green_taxi_etl
  schedule_interval: '@daily'
  schedule_type: time
  settings:
    landing_time_enabled: false
  sla: null
  start_time: 2024-02-09 05:00:00
  status: active
  variables: {}
